# coding: latin-1
###############################################################################
# Copyright (c) 2023 European Commission
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
###############################################################################


services:
  rp_registration:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    environment:
      FLASK_RUN_PORT: 5000
      SERVICE_URL: 'http://127.0.0.1:5000/'
      #Container path
      TRUSTED_CAS_PATH: 'app\certs'
      LOG_PATH: 'app\logs'
      VERIFIER: 'verifier-backend.eudiw.dev'

      SCA_SIGNER_URL: ''
      URL_STATUSLIST: ''
      WRPRC_PRIVATEkEY: 'app/EJBCA/ecdsa_key.pem'
      WRPRC_CERTIFICATE: 'app/EJBCA/ecdsa_cert.pem'

      DB_HOST: 'host.docker.internal'
      DB_PORT: 3306
      DB_USER: ''
      DB_PASSWORD: '' 
      DB_NAME: 'wrp'

      #EJBCA Settings
      CA_HOST: 
      CLIENTP12_ARCHIVE_FILEPATH: '/app/EJBCA/namefile.p12'
      MANAGMENT_CA: '/app/EJBCA/namefile.pem'
      CLIENTP12_ARCHIVE_PASSWORD: 
      EJBCA_USERNAME: 
      EJBCA_PASSWORD: 
      # Values required by the endpoint '/pkcs10enroll':
      CERTIFICATE_PROFILE_NAME: 
      END_ENTITY_PROFILE_NAME: 

    # local path : container path
    volumes:
      - ./CAs:/app/certs/CAs
      # CA and .p12 local directory : directory path in container
      - ./EJBCA:/app/EJBCA


