services:
  rp_registration:
    image: ghcr.io/niscy-eudiw/eudi-srv-web-relyingparty-registration-py:latest
    container_name: rp_registration
    ports:
      - "5000:5000"
    environment:
      FLASK_RUN_PORT: 5000
      SERVICE_URL: "http://127.0.0.1:5000/"
      #Container path
      TRUSTED_CAS_PATH: "/app/certs/CAs"
      VERIFIER: "verifier-backend.eudiw.dev"
      LOG_PATH: "/app/logs"
      DB_HOST: "host.docker.internal"
      DB_PORT: 
      DB_USER: 
      DB_PASSWORD: 
      DB_NAME: "relyingparty_reg"

      #EJBCA Settings
      cahost: 
      clientP12ArchiveFilepath: "/app/EJBCA/namefile.p12"
      managementCA: "/app/EJBCA/namefile.pem"
      clientP12ArchivePassword: 
      EJBCA_username: 
      EJBCA_password: 
      # Values required by the endpoint "/pkcs10enroll":
      certificateProfileName: 
      endEntityProfileName: 

    # local path : container path
    volumes:
      - ./CAs:/app/certs/CAs
      # CA and .p12 local directory : directory path in container
      - ./EJBCA:/app/EJBCA


